#cloud-config
# Generated by SKStacks tofu hetzner-cluster module

hostname: ${hostname}
manage_etc_hosts: true

users:
  - name: ubuntu
    groups: [sudo]
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ${ssh_pub_key}

package_update: true
package_upgrade: true

packages:
  - curl
  - wget
  - tar
  - open-iscsi    # Longhorn
  - nfs-common    # NFS PVs
  - iptables
  - ipvsadm
  - conntrack
  - socat
  - jq
  - gnupg         # CapAuth GPG
%{ for pkg in extra_packages ~}
  - ${pkg}
%{ endfor ~}

runcmd:
  # Disable swap
  - swapoff -a
  - sed -i 's|^[^#].*swap.*|#&|' /etc/fstab

  # Required kernel modules for RKE2/Canal
  - modprobe br_netfilter
  - modprobe overlay
  - echo -e "br_netfilter\noverlay" > /etc/modules-load.d/rke2.conf

  # Sysctl for K8s
  - |
    cat > /etc/sysctl.d/99-kubernetes.conf <<EOF
    net.ipv4.ip_forward = 1
    net.bridge.bridge-nf-call-iptables = 1
    net.bridge.bridge-nf-call-ip6tables = 1
    fs.inotify.max_user_instances = 8192
    fs.inotify.max_user_watches = 524288
    vm.overcommit_memory = 1
    EOF
    sysctl --system

  # Enable iscsid (Longhorn)
  - systemctl enable --now iscsid

final_message: |
  SKStacks node ${hostname} is ready for RKE2 installation.
  Cloud-init completed in $UPTIME seconds.
