apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - metallb-config.yaml
  - cluster-issuer.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  skstacks.io/managed: "true"
