apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

commonLabels:
  skstacks.io/env: dev

patches:
  - path: patches/metallb-config.yaml
  - path: patches/cluster-issuer.yaml
